services:
  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # Fixed port mapping
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - app-network
    # Removed all MONGO_INITDB_ROOT_* environment variables

  forrealdatingapp-server:
    build:
      context: ./contents
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./contents:/app
      - node_modules:/app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false
      # Removed all authentication-related variables
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - app-network

volumes:
  mongo-data:
  mongo-config:
  node_modules:

networks:
  app-network:
    driver: bridge