services:
  mongo:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - app-network

  forrealdatingapp-server:
    build:
      context: ./contents
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - EXPRESS=${EXPRESS}
      - TCP=${TCP}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URL=mongodb://root:password@mongo:27017/
      - GMAIL_SMTP_EMAIL=${GMAIL_SMTP_EMAIL}
      - GMAIL_SMTP_PASSWORD=${GMAIL_SMTP_PASSWORD}
    volumes:
      - ./contents:/app
      - node_modules:/app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: password
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - app-network

volumes:
  mongo-data:
  mongo-config:
  node_modules:

networks:
  app-network:
    driver: bridge